# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix,lf]
  - id: trailing-whitespace

# Black, the python code formatter
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    exclude: ^(docs)

# flake8 for python linting
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

# Sort your python imports in a standard form
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
