name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: 0
    - uses: bencherdev/bencher@46d007c103827da37db1a25b705dc73d3aaff7e6 # v0.6.3
    - name: ccache
      uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
      with:
        key: benchmark-ubuntu
    - name: Configure and Build
      run: |
        CXXFLAGS="-O3 -march=x86-64-v3" cmake -B build -DSLANG_INCLUDE_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE
        cmake --build build -j8
    - name: Run and submit benchmarks
      run: |
        bencher run \
        --project slang \
        --token '${{ secrets.BENCHER_API_TOKEN }}' \
        --branch master \
        --testbed ubuntu-latest \
        --adapter json \
        --github-actions '${{ secrets.GITHUB_TOKEN }}' \
        "tests/benchmarks/run_benchmarks.py --rtlmeter-dir build/_deps/rtlmeter-src run --slang build/bin/slang --bencher"
