name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      BUILD_FLAGS: -DSLANG_CI_BUILD=ON -DSLANG_INCLUDE_UVM_TEST=ON
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: clang-sanitize
            os: ubuntu-latest
          - preset: gcc-release
            os: ubuntu-24.04-arm
          - preset: gcc-11-release
            os: ubuntu-latest
          - preset: gcc-debug-shared
            os: ubuntu-latest
          - preset: gcc-debug-noexcept
            os: ubuntu-latest
          - preset: macos-release
            os: macos-latest
          - preset: win64-release
            os: windows-latest
          - preset: win64-arm-release
            os: windows-11-arm
          - preset: win64-debug-noexcept
            os: windows-latest
          - preset: wasi-sdk
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install dependencies
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main"
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y g++-16 g++-11 clang-22 clang-tidy-22
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.23
      with:
        key: ${{ matrix.preset }}
    - uses: konsumer/install-wasi-sdk@v1
      if: ${{ startsWith(matrix.preset, 'wasi-') }}
    - uses: bytecodealliance/actions/wasmtime/setup@v1
      if: ${{ startsWith(matrix.preset, 'wasi-') }}
    - name: Build
      if: ${{ !startsWith(matrix.preset, 'wasi-') && !startsWith(matrix.preset, 'win64') }}
      run: |
        cmake --preset ${{ matrix.preset }} $BUILD_FLAGS
        cmake --build build/${{ matrix.preset }} -j8
    - name: Build (Windows)
      if: ${{ startsWith(matrix.preset, 'win64') }}
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\${{ contains(matrix.preset, 'arm') && 'vcvarsarm64.bat' || 'vcvars64.bat' }}"
        cmake --preset ${{ matrix.preset }} ${{ env.BUILD_FLAGS }}
        cmake --build build/${{ matrix.preset }} -j8
    - name: Build (WASI)
      if: ${{ startsWith(matrix.preset, 'wasi-') }}
      run: |
        cmake -B build/${{ matrix.preset }} -DCMAKE_TOOLCHAIN_FILE=${WASI_SDK_PATH}/share/cmake/${{ matrix.preset }}.cmake -DSLANG_USE_THREADS=${{ contains(matrix.preset, 'pthread') && 'ON' || 'OFF' }} $BUILD_FLAGS
        cmake --build build/${{ matrix.preset }} -j8
    - name: Run tests
      run: ctest --test-dir build/${{ matrix.preset }} --output-on-failure --no-tests=error -j8
