name: dist
on:
  workflow_dispatch:
  push:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Build SDist
      run: pipx run build --sdist
    - name: Check metadata
      run: pipx run twine check dist/*
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz
        name: artifact-sdist

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: maxim-lobanov/setup-xcode@v1
      if: matrix.os == 'macos-latest'
      with:
        xcode-version: 'latest'
    - uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS_MACOS: auto universal2
        MACOSX_DEPLOYMENT_TARGET: "10.15"
    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: artifact-${{ matrix.os }}

  upload_test:
    name: Upload test
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - uses: actions/download-artifact@v4
      with:
        pattern: artifact-*
        path: dist
        merge-multiple: true
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip_existing: true

  upload_official:
    name: Upload official
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - uses: actions/download-artifact@v4
      with:
        pattern: artifact-*
        path: dist
        merge-multiple: true
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
