//------------------------------------------------------------------------------
// BlockSymbols.h
// Contains block-related hierarchy symbol definitions.
//
// File is under the MIT license; see LICENSE for details.
//------------------------------------------------------------------------------
#pragma once

#include "slang/binding/Statements.h"
#include "slang/symbols/SemanticFacts.h"
#include "slang/symbols/Symbol.h"

namespace slang {

class StatementBlockSymbol : public Symbol, public Scope {
public:
    StatementBlockKind blockKind;

    StatementBlockSymbol(Compilation& compilation, string_view name, SourceLocation loc,
                         StatementBlockKind blockKind) :
        Symbol(SymbolKind::StatementBlock, name, loc),
        Scope(compilation, this), blockKind(blockKind) {}

    void setTemporaryParent(const Scope& scope, SymbolIndex index) { setParent(scope, index); }
    const Statement& getBody() const;

    void toJson(json&) const {}

    static StatementBlockSymbol& fromSyntax(const Scope& scope, const BlockStatementSyntax& syntax);
    static StatementBlockSymbol& fromSyntax(const Scope& scope,
                                            const ForLoopStatementSyntax& syntax);
    static StatementBlockSymbol& fromSyntax(const Scope& scope,
                                            const ForeachLoopStatementSyntax& syntax);
    static StatementBlockSymbol& fromLabeledStmt(const Scope& scope, const StatementSyntax& syntax);

    static bool isKind(SymbolKind kind) { return kind == SymbolKind::StatementBlock; }

private:
    StatementBinder binder;
};

struct ProceduralBlockSyntax;

class ProceduralBlockSymbol : public Symbol {
public:
    ProceduralBlockKind procedureKind;

    ProceduralBlockSymbol(SourceLocation loc, ProceduralBlockKind procedureKind) :
        Symbol(SymbolKind::ProceduralBlock, "", loc), procedureKind(procedureKind) {}

    const Statement& getBody() const;
    void toJson(json& j) const;

    static ProceduralBlockSymbol& fromSyntax(
        const Scope& scope, const ProceduralBlockSyntax& syntax,
        span<const StatementBlockSymbol* const>& additionalBlocks);

    static bool isKind(SymbolKind kind) { return kind == SymbolKind::ProceduralBlock; }

private:
    StatementBinder binder;
};

struct CaseGenerateSyntax;
struct IfGenerateSyntax;
struct GenerateBlockSyntax;

/// Represents blocks that are instantiated by a loop generate or conditional
/// generate construct.
class GenerateBlockSymbol : public Symbol, public Scope {
public:
    uint32_t constructIndex = 0;
    bool isInstantiated = false;

    GenerateBlockSymbol(Compilation& compilation, string_view name, SourceLocation loc,
                        uint32_t constructIndex, bool isInstantiated) :
        Symbol(SymbolKind::GenerateBlock, name, loc),
        Scope(compilation, this), constructIndex(constructIndex), isInstantiated(isInstantiated) {}

    void toJson(json& j) const;

    static void fromSyntax(Compilation& compilation, const IfGenerateSyntax& syntax,
                           LookupLocation location, const Scope& parent, uint32_t constructIndex,
                           bool isInstantiated, SmallVector<GenerateBlockSymbol*>& results);

    static void fromSyntax(Compilation& compilation, const CaseGenerateSyntax& syntax,
                           LookupLocation location, const Scope& parent, uint32_t constructIndex,
                           bool isInstantiated, SmallVector<GenerateBlockSymbol*>& results);

    static GenerateBlockSymbol& fromSyntax(const Scope& scope, const GenerateBlockSyntax& syntax,
                                           uint32_t constructIndex);

    static bool isKind(SymbolKind kind) { return kind == SymbolKind::GenerateBlock; }
};

struct LoopGenerateSyntax;

/// Represents an array of generate blocks, as generated by a loop generate construct.
class GenerateBlockArraySymbol : public Symbol, public Scope {
public:
    struct ArrayEntry {
        not_null<const SVInt*> index;
        not_null<const GenerateBlockSymbol*> block;
    };

    span<const ArrayEntry> entries;
    uint32_t constructIndex;
    bool valid = false;

    GenerateBlockArraySymbol(Compilation& compilation, string_view name, SourceLocation loc,
                             uint32_t constructIndex) :
        Symbol(SymbolKind::GenerateBlockArray, name, loc),
        Scope(compilation, this), constructIndex(constructIndex) {}

    void toJson(json& j) const;

    /// Creates a generate block array from the given loop-generate syntax node.
    static GenerateBlockArraySymbol& fromSyntax(Compilation& compilation,
                                                const LoopGenerateSyntax& syntax,
                                                SymbolIndex scopeIndex, LookupLocation location,
                                                const Scope& parent, uint32_t constructIndex);

    static bool isKind(SymbolKind kind) { return kind == SymbolKind::GenerateBlockArray; }
};

} // namespace slang